on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+.[0-9]+' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Upload Release Asset

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build project # This would actually build your project, using zip for an example artifact
        run: |
          ROOT_DIR=$(pwd)
          mkdir -p ${ROOT_DIR}/build
          mkdir -p ${ROOT_DIR}/build/event-logger_${{ github.ref_name }}
          cp ${ROOT_DIR}/*.lua ${ROOT_DIR}/*.json ${ROOT_DIR}/*.png ${ROOT_DIR}/build/event-logger_${{ github.ref_name }}/.
          cd ${ROOT_DIR}/build || exit 1
          sed -i "s/@@VERSION@@/${{ github.ref_name }}/g" event-logger_${{ github.ref_name }}/info.json
          zip -r ${ROOT_DIR}/build/event-logger_${{ github.ref_name }}.zip event-logger_${{ github.ref_name }}
      - name: Create Release
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURR_TAG: ${{ github.ref_name }}
        run: |
          set +e
          PREV_TAG=$(git describe --tags --abbrev=0 ${CURR_TAG}^ 2> /dev/null)
          set -e
          if [ -z "${PREV_TAG}" ]; then
            RELEASE_NOTES=$(git log --format=%B -n 1 ${CURR_TAG})
          else
            TAG_RANGE="${PREV_TAG}..${CURR_TAG}"
            NUM_COMMITS=$(($(git rev-list --count "${TAG_RANGE}" 2> /dev/null) - 1))
            RELEASE_NOTES=$(git log --format=%B -n ${NUM_COMMITS} "${TAG_RANGE}")
          fi
          gh release create "${CURR_TAG}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="Release ${CURR_TAG}" \
              --notes="${RELEASE_NOTES}"
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
          CURR_TAG: ${{ github.ref_name }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./build/event-logger_${{ github.ref_name }}.zip
          asset_name: event-logger_${{ github.ref_name }}.zip
          asset_content_type: application/zip
